# Generated by Django 3.1.7 on 2021-03-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSECase',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('confirmedcovidcases', models.IntegerField()),
                ('totalconfirmedcovidcases', models.IntegerField()),
                ('confirmedcoviddeaths', models.IntegerField()),
                ('totalcoviddeaths', models.IntegerField()),
                ('statisticsprofiledate', models.DateField()),
                ('covidcasesconfirmed', models.IntegerField(blank=True, null=True)),
                ('hospitalisedcovidcases', models.IntegerField(blank=True, null=True)),
                ('requiringicucovidcases', models.IntegerField(blank=True, null=True)),
                ('healthcareworkerscovidcases', models.IntegerField(blank=True, null=True)),
                ('clustersnotified', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged5', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged5to14', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged15to24', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged25to34', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged35to44', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged45to54', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged55to64', models.IntegerField(blank=True, null=True)),
                ('hospitalisedaged65up', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('unknown', models.IntegerField(blank=True, null=True)),
                ('aged1to4', models.IntegerField(blank=True, null=True)),
                ('aged5to14', models.IntegerField(blank=True, null=True)),
                ('aged15to24', models.IntegerField(blank=True, null=True)),
                ('aged25to34', models.IntegerField(blank=True, null=True)),
                ('aged35to44', models.IntegerField(blank=True, null=True)),
                ('aged45to54', models.IntegerField(blank=True, null=True)),
                ('aged55to64', models.IntegerField(blank=True, null=True)),
                ('aged65up', models.IntegerField(blank=True, null=True)),
                ('median_age', models.IntegerField(blank=True, null=True)),
                ('communitytransmission', models.IntegerField()),
                ('closecontact', models.IntegerField()),
                ('travelabroad', models.IntegerField()),
                ('fid', models.IntegerField()),
            ],
            options={
                'db_table': 'hse_cases',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JohnHopkinsCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recoveries', models.FloatField()),
            ],
            options={
                'db_table': 'john_hopkins_cases',
                'ordering': ['-date'],
                'unique_together': {('date', 'country', 'cases', 'deaths', 'recoveries')},
            },
        ),
    ]
