# Generated by Django 3.1.7 on 2021-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSECounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origid', models.IntegerField()),
                ('countyname', models.IntegerField()),
                ('populationcensus16', models.IntegerField()),
                ('igeasting', models.IntegerField()),
                ('ignorthing', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
                ('uniquegeographicidentifier', models.IntegerField()),
                ('confirmedcovidcases', models.IntegerField()),
                ('populationproportioncovidcases', models.IntegerField()),
                ('confirmedcoviddeaths', models.IntegerField()),
                ('confirmedcovidrecovered', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('fid', models.DateField()),
                ('timestampdate', models.DateField()),
            ],
            options={
                'db_table': 'hse_counties',
                'ordering': ['-timestampdate'],
            },
        ),
    ]
