# Generated by Django 3.1.7 on 2021-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_hsecounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsecounty',
            name='confirmedcoviddeaths',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='confirmedcovidrecovered',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='countyname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='populationproportioncovidcases',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='uniquegeographicidentifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsecounty',
            name='y',
            field=models.FloatField(),
        ),
    ]
