# Generated by Django 3.1.7 on 2021-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210308_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedcovidcases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
