# Generated by Django 3.1.7 on 2021-03-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_remove_covid_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='covid',
            unique_together={('date', 'country', 'cases', 'deaths', 'recovered')},
        ),
    ]
