# Generated by Django 3.1.7 on 2021-03-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210303_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={'managed': False},
        ),
    ]
