# Generated by Django 3.1.7 on 2021-03-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210303_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={},
        ),
    ]
