# Generated by Django 3.1.7 on 2021-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210308_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsecase',
            name='aged15to24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged1to4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged25to34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged35to44',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged45to54',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged55to64',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged5to14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='aged65up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='clustersnotified',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged15to24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged25to34',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged35to44',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged45to54',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged55to64',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged5to14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='hospitalisedaged65up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='median_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsecase',
            name='unknown',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
