# Generated by Django 3.1.7 on 2021-03-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20210303_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid',
            old_name='recovered',
            new_name='recoveries',
        ),
        migrations.AlterUniqueTogether(
            name='covid',
            unique_together={('date', 'country', 'cases', 'deaths', 'recoveries')},
        ),
    ]
