# Generated by Django 3.1.7 on 2021-03-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210310_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseswab',
            name='pos1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hseswab',
            name='posr1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
