# Generated by Django 3.1.7 on 2021-03-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210303_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={'ordering': ['-date']},
        ),
    ]
