# Generated by Django 3.1.7 on 2021-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210317_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsecase',
            old_name='hospitalisedaged65up',
            new_name='hospitalisedaged65to74',
        ),
        migrations.AddField(
            model_name='hsecase',
            name='hospitalisedaged75to84',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsecase',
            name='hospitalisedaged85up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
