# Generated by Django 3.1.7 on 2021-03-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210303_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covid',
            new_name='JohnHopkins',
        ),
        migrations.AlterModelTable(
            name='johnhopkins',
            table='john_hopkins',
        ),
    ]
