# Generated by Django 3.1.7 on 2021-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20210405_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsecase',
            old_name='aged65up',
            new_name='aged65to74',
        ),
        migrations.AddField(
            model_name='hsecase',
            name='aged75to84',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsecase',
            name='aged85up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
