# Generated by Django 3.1.7 on 2021-03-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20210306_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JohnHopkins',
            new_name='Case',
        ),
        migrations.AlterModelTable(
            name='case',
            table='cases',
        ),
    ]
