# Generated by Django 3.1.7 on 2021-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20210405_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsecase',
            name='aged65up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsecase',
            name='hospitalisedaged65up',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
