# Generated by Django 3.1.7 on 2021-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20210306_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSECase',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('confirmed_covid_cases', models.IntegerField()),
                ('total_confirmed_covid_cases', models.IntegerField()),
                ('confirmed_covid_deaths', models.IntegerField()),
                ('total_covid_deaths', models.IntegerField()),
                ('statistics_profile_date', models.DateTimeField()),
                ('covid_cases_confirmed', models.IntegerField()),
                ('hospitalised_covid_cases', models.IntegerField()),
                ('requiring_icu_covid_cases', models.IntegerField()),
                ('healthcare_workers_covid_cases', models.IntegerField()),
                ('clusters_notified', models.IntegerField()),
                ('hospitalised_aged5', models.IntegerField()),
                ('hospitalised_aged_5_to_14', models.IntegerField()),
                ('hospitalised_aged_15_to_24', models.IntegerField()),
                ('hospitalised_aged_25_to_34', models.IntegerField()),
                ('hospitalised_aged_35_to_44', models.IntegerField()),
                ('hospitalised_aged_45_to_54', models.IntegerField()),
                ('hospitalised_aged_55_to_64', models.IntegerField()),
                ('hospitalised_aged_65_up', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('aged_1_to_4', models.IntegerField()),
                ('aged_5_to_14', models.IntegerField()),
                ('aged_15_to_24', models.IntegerField()),
                ('aged_25_to_34', models.IntegerField()),
                ('aged_35_to_44', models.IntegerField()),
                ('aged_45_to_54', models.IntegerField()),
                ('aged_55_to_64', models.IntegerField()),
                ('aged_65_up', models.IntegerField()),
                ('median_age', models.IntegerField()),
                ('community_transmission', models.IntegerField()),
                ('close_contact', models.IntegerField()),
                ('travel_abroad', models.IntegerField()),
                ('fid', models.IntegerField()),
            ],
            options={
                'db_table': 'hse_cases',
                'ordering': ['-date'],
            },
        ),
    ]
